services:
  vault:
    container_name: vault
    hostname: vault
    image: "localhost/vault:latest"
    init: true
    environment:
      VAULT_ADDR: "http://0.0.0.0:8300"
    cap_add:
      - IPC_LOCK
    build: .
    ports:
      - "8300:8300"
